exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('events').del()
  await knex('events').insert([
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Poker',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '1',
      IMG: 'CasualGame.jpg',
      description: 'Poker @ the casino',
      coordsX: -36.8491313,
      coordsY: 174.7617643,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Feed at 8',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '4',
      IMG: 'CasualGame.jpg',
      description: 'fikas on',
      coordsX: -36.85741495,
      coordsY: 174.76362126533706,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Watch ABs at eden park',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '4',
      IMG: 'Sports.jpg',
      description: 'go the ABs',
      coordsX: 36.8750352,
      coordsY: 174.7440567126547,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Harry',
    },
    {
      name: 'Skate',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '12',
      IMG: 'Sport.jpg',
      description: 'X games mode',
      coordsX: 52.5170365,
      coordsY: 13.3888599,
      category: 'Sports',
      display_name: 'Berlin',
      attendees: 'Uncle Bob',
    },
    //upcoming
    {
      name: 'Celtics to win finals',
      status: 'previous',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'Sports.jpg',
      description: '19!!!',
      coordsX: 45.378820450000006,
      coordsY: -75.66873348444389,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    //past events
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
    {
      name: 'Tag',
      status: 'current',
      date: '20/7/2021',
      time: 'arvo',
      max: '6',
      IMG: 'CasualGame.jpg',
      description: 'tag at vic park, need 6 to make a game and run a few subs',
      coordsX: -36.86447,
      coordsY: 174.7763,
      category: 'Sports',
      display_name:
        'Sydney, Council of the City of Sydney, New South Wales, Australia',
      attendees: 'Uncle Bob',
    },
  ])
}
